from .audiomack import *
from .soundcloud import *
from .nhaccuatui import *
from .zingmp3 import *
from .mixcloud import *
from .youtubemusic import *
from .spotify import *
from src.bot.command.menuBot import InitTimeoutMenu
from src.command.api.browser.tikwm import *
from functions.services.hook.bot_hook.im_core import *
